version: '2'

services:
  app:
    build:
      context: .
    environment: 
      - SQLALCHEMY_DATABASE_URI=postgres://test:password@db:5432/testdb
    ports: 
      - "5000:5000"
    volumes: 
      - ./:/app
    depends_on:
      - db
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password